### ISSUE TITLE
Add Github action PR check

### ISSUE THREAD

**Issue by wulfmann** [wulfmann/aws-coco#1]
I'd like to add a github action that runs the following checks on pull requests

- python black (poetry run black .)
- pytest (poetry run pytest when we have tests)

**Comment by DanB288** [comment]
Hey Wulfmann!!  I would like to work on this issue👍

**Comment by joaofix** [comment]
@DanB288 , I implement this on #3

**Comment by wulfmann** [comment]
Thanks for the interest and work on this! Since #3 is merged i will close this.

**Comment by wulfmann** [comment]
@DanB288 it looks like you were beaten to the punch on this issue, but i added a few more if you’re interested in contributing still!

**Comment by DanB288** [comment]
Thanks a lot @wulfmann . Always interested in contributing 😉👍
